services:
  keycloak:
    image: quay.io/keycloak/keycloak:26.2.5
    container_name: keycloak-dev
    ports:
      - "8181:8080"
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
      KC_HOSTNAME: 192.168.68.180
      KC_HOSTNAME_PORT: 8181
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_BACKCHANNEL: false
    command: start-dev
    restart: unless-stopped
    volumes:
      - ./keycloak_data:/opt/keycloak/data