http_port 3128
acl localnet src 192.168.0.0/24
acl Safe_methods method GET POST OPTIONS CONNECTS
http_access allow localnet Safe_methods
http_access deny all
#http_access allow all
cache_dir ufs /var/spool/squid 100 16 256
access_log /var/log/squid/access.log squid
#dns_v4_first on
